version: "3"

services:
  node-app:
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      # - /app/node_modules # to avoid copy this folder
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    env_file:
      - ./.env

