version: "3"

services:
  node-app:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=SamuProd
    ports:
      - "8081:80"
    # environment:
    #   - PORT=4000
    env_file:
      - ./.env

