version: "3"

services:
  node-app:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # environment:
    #   - PORT=4000
    env_file:
      - ./.env

